sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

env:
  - DOCKER_IMAGE=rso1920/channels:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - DOCKER_LATEST=rso1920/channels:latest

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
  - docker tag "$DOCKER_IMAGE" "$DOCKER_LATEST"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
  - docker push "$DOCKER_LATEST"
