apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-channels-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-channels
  template:
    metadata:
      labels:
        app: rso1920-channels
    spec:
      containers:
      - image: rso1920/channels:latest
        name: rso1920-channels
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://10.28.2.163:8080
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://35.241.190.224:5432/channels
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
            value: http://etcd:2379/health
        ports:
        - containerPort: 8080
          name: server-channel
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: server-channel
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server-channel
          initialDelaySeconds: 60
          periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-channels
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: server-channel
  selector:
    app: rso1920-channels
